name: This is a github action
run-name: This is run name kiki kiki
on: [push]
jobs: 
  Echo:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v4
    - name: cat temp.txt
      run: cat temp.txt
